---
output_root: data/pas_out
bucket: gcp-utr-variants-test
cluster: utr-variant-chr22
local: true
genome_assembly: GRCh37
gnomAD:
  subset: '22:1-51304566' # end: 51304566
  version: 2.1.1
  gnomAD_ht: gs://gcp-public-data--gnomad/release/2.1.1/ht/genomes/gnomad.genomes.r2.1.1.sites.ht
  context_ht: gs://gnomad-public/papers/2019-flagship-lof/v1.0/context/Homo_sapiens_assembly19.fasta.snps_only.vep_20181129.ht
  #coverage_ht: gs://gcp-public-data--gnomad/release/2.1/coverage/exomes/gnomad.exomes.r2.1.coverage.ht
  mutation_rate_ht: gs://gnomad-public/papers/2019-flagship-lof/v1.0/model/mutation_rate_methylation_bins.ht
databases:
  APAatlas_DaPars:
    APA: data/annotations/APAatlas/DaPars/PDUI.txt
    annotation: data/annotations/APAatlas/DaPars/hg19_refseq_extracted_3UTR.bed
    chr_style: chr
  APAatlas_SAAP-RS:
    APA: data/annotations/APAatlas/SAAP-RS/RED.txt
    annotation: data/annotations/APAatlas/SAAP-RS/RED_3UTR_annotation_hg19.txt
    chr_style: chr
  PolyA_DB:
    file: data/annotations/PolyA_DB3/human.PAS.txt
    chr_style: chr
  Gencode:
    file: data/annotations/GRCh37/gencode.v36lift37.annotation.chr22.gff3.gz
    chr_style: chr
