name: pas_anno
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - pip
  - gcc_linux-64
  - gxx_linux-64
  - libopenblas
  - liblapack
  - openjdk=8
  - igv>=2.4
  - snakemake=5
  - htslib
  - bedtools>=2.29
  - bedops>=2.4
  - pybedtools
  - matplotlib
  - seaborn
  - genomepy
  - pysam
  - pip:
    - hail>=0.2.61
    - gnomad>=0.4
